// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type firewallIn6Addr struct {
	_    structs.HostLayout
	In6U struct {
		_       structs.HostLayout
		U6Addr8 [16]uint8
	}
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	firewallMapIpv4BlackList = "ipv4_black_list"
	firewallMapIpv6BlackList = "ipv6_black_list"
	firewallProgXdpFirewall  = "xdp_firewall"
)

// loadFirewall returns the embedded CollectionSpec for firewall.
func loadFirewall() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FirewallBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load firewall: %w", err)
	}

	return spec, err
}

// loadFirewallObjects loads firewall and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*firewallObjects
//	*firewallPrograms
//	*firewallMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFirewallObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadFirewall()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// firewallSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallSpecs struct {
	firewallProgramSpecs
	firewallMapSpecs
	firewallVariableSpecs
}

// firewallProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallProgramSpecs struct {
	XdpFirewall *ebpf.ProgramSpec `ebpf:"xdp_firewall"`
}

// firewallMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallMapSpecs struct {
	Ipv4BlackList *ebpf.MapSpec `ebpf:"ipv4_black_list"`
	Ipv6BlackList *ebpf.MapSpec `ebpf:"ipv6_black_list"`
}

// firewallVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallVariableSpecs struct {
}

// firewallObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallObjects struct {
	firewallPrograms
	firewallMaps
	firewallVariables
}

func (o *firewallObjects) Close() error {
	return _FirewallClose(
		&o.firewallPrograms,
		&o.firewallMaps,
	)
}

// firewallMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallMaps struct {
	Ipv4BlackList *ebpf.Map `ebpf:"ipv4_black_list"`
	Ipv6BlackList *ebpf.Map `ebpf:"ipv6_black_list"`
}

func (m *firewallMaps) Close() error {
	return _FirewallClose(
		m.Ipv4BlackList,
		m.Ipv6BlackList,
	)
}

// firewallVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallVariables struct {
}

// firewallPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallPrograms struct {
	XdpFirewall *ebpf.Program `ebpf:"xdp_firewall"`
}

func (p *firewallPrograms) Close() error {
	return _FirewallClose(
		p.XdpFirewall,
	)
}

func _FirewallClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed firewall_bpfeb.o
var _FirewallBytes []byte
