// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type load_balancerBackend struct {
	_  structs.HostLayout
	Ip uint32
}

type load_balancerConfig struct {
	_     structs.HostLayout
	Vip   uint32
	Base  uint32
	Count uint32
	Port  uint16
	Pad   uint16
}

type load_balancerCtKey struct {
	_     structs.HostLayout
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
	Proto uint8
	Pad   [3]uint8
}

type load_balancerCtVal struct {
	_        structs.HostLayout
	ClientIp uint32
	Vip      uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	load_balancerMapBackends        = "backends"
	load_balancerMapConfigs         = "configs"
	load_balancerMapConntrack       = "conntrack"
	load_balancerProgXdpLoadBalance = "xdp_load_balance"
)

// loadLoad_balancer returns the embedded CollectionSpec for load_balancer.
func loadLoad_balancer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Load_balancerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load load_balancer: %w", err)
	}

	return spec, err
}

// loadLoad_balancerObjects loads load_balancer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*load_balancerObjects
//	*load_balancerPrograms
//	*load_balancerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLoad_balancerObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadLoad_balancer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// load_balancerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type load_balancerSpecs struct {
	load_balancerProgramSpecs
	load_balancerMapSpecs
	load_balancerVariableSpecs
}

// load_balancerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type load_balancerProgramSpecs struct {
	XdpLoadBalance *ebpf.ProgramSpec `ebpf:"xdp_load_balance"`
}

// load_balancerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type load_balancerMapSpecs struct {
	Backends  *ebpf.MapSpec `ebpf:"backends"`
	Configs   *ebpf.MapSpec `ebpf:"configs"`
	Conntrack *ebpf.MapSpec `ebpf:"conntrack"`
}

// load_balancerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type load_balancerVariableSpecs struct {
}

// load_balancerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLoad_balancerObjects or ebpf.CollectionSpec.LoadAndAssign.
type load_balancerObjects struct {
	load_balancerPrograms
	load_balancerMaps
	load_balancerVariables
}

func (o *load_balancerObjects) Close() error {
	return _Load_balancerClose(
		&o.load_balancerPrograms,
		&o.load_balancerMaps,
	)
}

// load_balancerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLoad_balancerObjects or ebpf.CollectionSpec.LoadAndAssign.
type load_balancerMaps struct {
	Backends  *ebpf.Map `ebpf:"backends"`
	Configs   *ebpf.Map `ebpf:"configs"`
	Conntrack *ebpf.Map `ebpf:"conntrack"`
}

func (m *load_balancerMaps) Close() error {
	return _Load_balancerClose(
		m.Backends,
		m.Configs,
		m.Conntrack,
	)
}

// load_balancerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLoad_balancerObjects or ebpf.CollectionSpec.LoadAndAssign.
type load_balancerVariables struct {
}

// load_balancerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLoad_balancerObjects or ebpf.CollectionSpec.LoadAndAssign.
type load_balancerPrograms struct {
	XdpLoadBalance *ebpf.Program `ebpf:"xdp_load_balance"`
}

func (p *load_balancerPrograms) Close() error {
	return _Load_balancerClose(
		p.XdpLoadBalance,
	)
}

func _Load_balancerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed load_balancer_bpfel.o
var _Load_balancerBytes []byte
