// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type rate_limiterPacketMetadata struct {
	_           structs.HostLayout
	WindowStart uint64
	Packets     uint32
	_           [4]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	rate_limiterMapMetadata      = "metadata"
	rate_limiterMapRateLimit     = "rate_limit"
	rate_limiterProgXdpRateLimit = "xdp_rate_limit"
)

// loadRate_limiter returns the embedded CollectionSpec for rate_limiter.
func loadRate_limiter() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Rate_limiterBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load rate_limiter: %w", err)
	}

	return spec, err
}

// loadRate_limiterObjects loads rate_limiter and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*rate_limiterObjects
//	*rate_limiterPrograms
//	*rate_limiterMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadRate_limiterObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadRate_limiter()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// rate_limiterSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rate_limiterSpecs struct {
	rate_limiterProgramSpecs
	rate_limiterMapSpecs
	rate_limiterVariableSpecs
}

// rate_limiterProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rate_limiterProgramSpecs struct {
	XdpRateLimit *ebpf.ProgramSpec `ebpf:"xdp_rate_limit"`
}

// rate_limiterMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rate_limiterMapSpecs struct {
	Metadata  *ebpf.MapSpec `ebpf:"metadata"`
	RateLimit *ebpf.MapSpec `ebpf:"rate_limit"`
}

// rate_limiterVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rate_limiterVariableSpecs struct {
}

// rate_limiterObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadRate_limiterObjects or ebpf.CollectionSpec.LoadAndAssign.
type rate_limiterObjects struct {
	rate_limiterPrograms
	rate_limiterMaps
	rate_limiterVariables
}

func (o *rate_limiterObjects) Close() error {
	return _Rate_limiterClose(
		&o.rate_limiterPrograms,
		&o.rate_limiterMaps,
	)
}

// rate_limiterMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadRate_limiterObjects or ebpf.CollectionSpec.LoadAndAssign.
type rate_limiterMaps struct {
	Metadata  *ebpf.Map `ebpf:"metadata"`
	RateLimit *ebpf.Map `ebpf:"rate_limit"`
}

func (m *rate_limiterMaps) Close() error {
	return _Rate_limiterClose(
		m.Metadata,
		m.RateLimit,
	)
}

// rate_limiterVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadRate_limiterObjects or ebpf.CollectionSpec.LoadAndAssign.
type rate_limiterVariables struct {
}

// rate_limiterPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadRate_limiterObjects or ebpf.CollectionSpec.LoadAndAssign.
type rate_limiterPrograms struct {
	XdpRateLimit *ebpf.Program `ebpf:"xdp_rate_limit"`
}

func (p *rate_limiterPrograms) Close() error {
	return _Rate_limiterClose(
		p.XdpRateLimit,
	)
}

func _Rate_limiterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed rate_limiter_bpfel.o
var _Rate_limiterBytes []byte
