// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	port_forwardMapPortsMap                       = "ports_map"
	port_forwardProgPortForwardLookupEchoDispatch = "port_forward_lookup_echo_dispatch"
)

// loadPort_forward returns the embedded CollectionSpec for port_forward.
func loadPort_forward() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Port_forwardBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load port_forward: %w", err)
	}

	return spec, err
}

// loadPort_forwardObjects loads port_forward and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*port_forwardObjects
//	*port_forwardPrograms
//	*port_forwardMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPort_forwardObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadPort_forward()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// port_forwardSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type port_forwardSpecs struct {
	port_forwardProgramSpecs
	port_forwardMapSpecs
	port_forwardVariableSpecs
}

// port_forwardProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type port_forwardProgramSpecs struct {
	PortForwardLookupEchoDispatch *ebpf.ProgramSpec `ebpf:"port_forward_lookup_echo_dispatch"`
}

// port_forwardMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type port_forwardMapSpecs struct {
	PortsMap *ebpf.MapSpec `ebpf:"ports_map"`
}

// port_forwardVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type port_forwardVariableSpecs struct {
}

// port_forwardObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPort_forwardObjects or ebpf.CollectionSpec.LoadAndAssign.
type port_forwardObjects struct {
	port_forwardPrograms
	port_forwardMaps
	port_forwardVariables
}

func (o *port_forwardObjects) Close() error {
	return _Port_forwardClose(
		&o.port_forwardPrograms,
		&o.port_forwardMaps,
	)
}

// port_forwardMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPort_forwardObjects or ebpf.CollectionSpec.LoadAndAssign.
type port_forwardMaps struct {
	PortsMap *ebpf.Map `ebpf:"ports_map"`
}

func (m *port_forwardMaps) Close() error {
	return _Port_forwardClose(
		m.PortsMap,
	)
}

// port_forwardVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadPort_forwardObjects or ebpf.CollectionSpec.LoadAndAssign.
type port_forwardVariables struct {
}

// port_forwardPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPort_forwardObjects or ebpf.CollectionSpec.LoadAndAssign.
type port_forwardPrograms struct {
	PortForwardLookupEchoDispatch *ebpf.Program `ebpf:"port_forward_lookup_echo_dispatch"`
}

func (p *port_forwardPrograms) Close() error {
	return _Port_forwardClose(
		p.PortForwardLookupEchoDispatch,
	)
}

func _Port_forwardClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed port_forward_bpfeb.o
var _Port_forwardBytes []byte
